#! /usr/bin/env bash

directory_basename=${PWD##*/}

if ! tmux has-session -t "$directory_basename"
then
    tmux new-session -s "$directory_basename" -n Server -d

    # create moar windows
    tmux new-window -t "$directory_basename":1 -n UI
    tmux new-window -t "$directory_basename":2 -n Tests
    tmux new-window -t "$directory_basename":3 -n Code
    tmux new-window -t "$directory_basename":4 -n Zsh

    # run some command in the first window
    if [ -z "$1" ]
    then
        tmux send-keys -t "$directory_basename":0.0 "cd ${PWD}" C-m
    else
        tmux send-keys -t "$directory_basename":0.0 "cd ${PWD} && ${1}" C-m
    fi

    tmux send-keys -t "$directory_basename":1.0 "cd ${PWD}" C-m
    tmux send-keys -t "$directory_basename":2.0 "cd ${PWD}" C-m
    tmux send-keys -t "$directory_basename":3.0 "cd ${PWD}" C-m
    tmux send-keys -t "$directory_basename":4.0 "cd ${PWD}" C-m

    # select the server window and pane
    tmux select-window -t "$directory_basename":0.0
fi
tmux attach -t "$directory_basename"
