#! /usr/bin/env bash
# find the local installation of eslint and run it

while IFS= read -r -d '' file
do
    if [[ -f "$file" ]]
    then
        "$file" "$@"
    fi
done <   <(find . -name 'eslint' -print0)

