#! /usr/bin/env bash

CC_DIR="${HOME}"/dev/command-center
set -x
pushd "${CC_DIR}" || exit
sudo docker-compose down
sudo docker network create local-net
./gradlew clean -PangularProfile=local bootJar -x :picnic-ui:npm_run_build
sudo docker-compose up -d --build --remove-orphans
sudo docker-compose logs --follow
popd || exit
