#! /usr/bin/env bash

PLATFORM=$(uname)

case $PLATFORM in
    Darwin)
        brew update
        brew upgrade
        brew upgrade --cask
        brew cleanup
        ;;
    Linux)
        sudo apt-get update
        sudo apt-get upgrade -y --allow-downgrades --with-new-pkgs
        sudo apt-get autoremove -y
        rustup update
        ;;
esac

