#! /usr/bin/env bash
PLATFORM=`uname`

case $PLATFORM in
    Darwin)
        brew update
        brew upgrade
        brew cask upgrade
        brew cleanup
        ;;
    Linux)
        sudo pacman --noconfirm -S archlinux-keyring # update the keyring
        sudo pacman --noconfirm -Syu # update the packages
        if pacman -Qtdq ; then
            sudo pacman --noconfirm -Rns $(pacman -Qtdq) # remove orphans
        fi
        ;;
esac

